include:
  - compose_files/nginx.yml
  - compose_files/database.yml
  - compose_files/auth-service.yml
  - compose_files/rabbitmq.yml
  - compose_files/product-catalog-service.yml
  - compose_files/recommendation-service.yml
  - compose_files/pgadmin.yml
  - compose_files/monitoring.yml

volumes:
  data:

networks:
  app-network:
    driver: bridge
