FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y netcat-traditional curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install pytest pytest-cov allure-pytest requests

COPY . .

RUN chmod +x /app
