FROM python:3.9-bookworm AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y curl --no-install-recommends && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN python3 -m ensurepip && python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --no-cache-dir pytest allure-pytest pytest-cov requests && \
    curl -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.1/allure-commandline-2.24.1.tgz | tar -xz -C /opt/ && \
    ln -s /opt/allure-2.24.1/bin/allure /usr/bin/allure

FROM python:3.9-slim-bookworm

WORKDIR /app

COPY --from=builder /opt/venv /opt/venv
COPY --from=builder /usr/bin/allure /usr/bin/allure
COPY --from=builder /opt/allure-2.24.1 /opt/allure-2.24.1

ENV PATH="/opt/venv/bin:$PATH"
ENV PATH="/opt/allure-2.24.1/bin:$PATH"

RUN apt-get update && apt-get install -y openjdk-17-jre-headless --no-install-recommends && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1
