FROM base-test:latest

WORKDIR /app

COPY go.mod go.sum ./
COPY vendor ./vendor
COPY src ./src

RUN apt-get update && \
    apt-get install -y wget && \
    wget https://go.dev/dl/go1.22.1.linux-amd64.tar.gz && \
    rm -rf /usr/local/go && tar -C /usr/local -xzf go1.22.1.linux-amd64.tar.gz && \
    rm go1.22.1.linux-amd64.tar.gz && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV PATH="/usr/local/go/bin:${PATH}"
ENV GO111MODULE=on
ENV CGO_ENABLED=0
ENV GOPATH=/root/go
ENV PATH="${GOPATH}/bin:${PATH}"

RUN go mod vendor

RUN go install gotest.tools/gotestsum@latest

CMD ["sh", "-c", "gotestsum --format testname --junitfile /app/allure-results/go-test-report.xml -- ./src/... -v"]
