services:
  frontend:
    build: ../frontend
    container_name: frontend
    restart: always
    env_file: "../.env"
    depends_on:
      auth-service:
        condition: service_started
      product-catalog-service:
        condition: service_started
      recommendation-service:
        condition: service_started
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/dist
    networks:
      - app-network
