services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file: "../.env"
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_started
    networks:
      - app-network
