services:
  product-catalog-service:
    build: ../backend/product-catalog-service
    container_name: product_catalog_service
    restart: unless-stopped
    command: >
      sh -c "
        while ! nc -z db 5432; do
          sleep 1
        done &&
        while ! nc -z rabbitmq 5672; do
          sleep 1
        done &&
        /app/main
      "
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file: "../.env"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/products/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - app-network
