global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth_service:8001']
  - job_name: 'product-catalog-service'
    static_configs:
      - targets: ['product_catalog_service:8081']

