services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
      - "15692:15692"
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
      - RABBITMQ_LOGS=${RABBITMQ_LOGS}
      - RABBITMQ_SASL_LOGS=${RABBITMQ_SASL_LOGS}
    env_file: "../.env"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app-network
    volumes:
      - ../rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
